[package]
name = "command-guardian"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"
nix = { version = "0.29.0", features = ["term", "fs"] }
signal-hook = "0.3.17"
termsize = "0.1.9"
